name: test and push to dockerhub
on: 
    push:
        branches: [ "main" ]
jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

          
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
           python-version: 3.x

        - name: Install Dependencies
          run: |
            pip install flask
          working-directory: .

        - name: Run Tests
          run: |
           python3 -m unittest test_app.py
          working-directory: .

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USER }}/custom-action:${{ github.sha }}